---
- name: running shell script with cron job
  hosts: localhost
  tasks: 

  - name: Display paths of all .txt files in dir
    ansible.builtin.debug: msg={{ lookup('ansible.builtin.fileglob', 'home/siddharth/niraj_devops/*.txt') }}

  - name: Copy each file over that matches the given pattern
    ansible.builtin.copy:
      src: "{{ item }}"
      dest: "/home/siddharth/Videos"
      owner: "siddharth"
      mode: 0600
    with_fileglob:
      - "home/siddharth/niraj_devops/*.txt"


#---------------------- end of play----------------------#
